name: royalgambit_recruitment_app
description: Royale Gambit recruitment app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.15
  chopper: ^8.1.0
  chopper_generator: ^8.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  stream_transform: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/logos/

spider:
  generate_tests: true
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false
  package: resources
  groups:
    - path: assets/icons
      class_name: AppIcons
      types: [ .svg ]
    - path: assets/images/logos
      class_name: LogoImages
      types: [ .svg ]
